#!/usr/bin/env python3
"""Compatibility shim for packaged subconscious scheduler."""

from __future__ import annotations

from aippocampus_runtime.subconscious.scheduler import (
    DEFAULT_API_KEY_ENV,
    DEFAULT_COOLDOWN_SECONDS,
    DEFAULT_ENQUEUE_COOLDOWN_SECONDS,
    DEFAULT_ENQUEUE_LOCK_STALE_SECONDS,
    DEFAULT_JOB_CONCURRENCY,
    DEFAULT_MAX_FINDINGS,
    DEFAULT_MAX_TURNS,
    DEFAULT_MIN_NEW_TURNS,
    DEFAULT_PROJECT_LEASE_SECONDS,
    DEFAULT_SAMPLES_PER_JOB,
    DEFAULT_STALE_LOCK_SECONDS,
    SCRIPT_DIR,
    STATE_SCHEMA_VERSION,
    FileLock,
    ProjectStats,
    bootstrap_project_state_from_staging,
    choose_projects,
    claim_project_lease,
    clear_project_lease,
    due_reason,
    finding_mentions_project,
    focus_for,
    iso_from_ts,
    latest_staging_ts,
    lease_active,
    load_json,
    load_state,
    log_path,
    main,
    maybe_start,
    maybe_start_locked,
    norm_path,
    objective_for,
    parse_utc_ts,
    project_for_cwd,
    project_stats_from_registry,
    registry_dir,
    registry_path,
    run_due,
    run_project,
    run_text,
    save_json,
    save_state,
    start_detached,
    state_path,
    thread_project_label,
    thread_workspace,
)

__all__ = [
    "DEFAULT_API_KEY_ENV",
    "DEFAULT_COOLDOWN_SECONDS",
    "DEFAULT_ENQUEUE_COOLDOWN_SECONDS",
    "DEFAULT_ENQUEUE_LOCK_STALE_SECONDS",
    "DEFAULT_JOB_CONCURRENCY",
    "DEFAULT_MAX_FINDINGS",
    "DEFAULT_MAX_TURNS",
    "DEFAULT_MIN_NEW_TURNS",
    "DEFAULT_PROJECT_LEASE_SECONDS",
    "DEFAULT_SAMPLES_PER_JOB",
    "DEFAULT_STALE_LOCK_SECONDS",
    "SCRIPT_DIR",
    "STATE_SCHEMA_VERSION",
    "FileLock",
    "ProjectStats",
    "bootstrap_project_state_from_staging",
    "choose_projects",
    "claim_project_lease",
    "clear_project_lease",
    "due_reason",
    "finding_mentions_project",
    "focus_for",
    "iso_from_ts",
    "latest_staging_ts",
    "lease_active",
    "load_json",
    "load_state",
    "log_path",
    "main",
    "maybe_start",
    "maybe_start_locked",
    "norm_path",
    "objective_for",
    "parse_utc_ts",
    "project_for_cwd",
    "project_stats_from_registry",
    "registry_dir",
    "registry_path",
    "run_due",
    "run_project",
    "run_text",
    "save_json",
    "save_state",
    "start_detached",
    "state_path",
    "thread_project_label",
    "thread_workspace",
]

if __name__ == "__main__":
    raise SystemExit(main())
