from __future__ import annotations

from typing import NamedTuple


class TestModuleClassification(NamedTuple):
    primary_tier: str
    tags: tuple[str, ...] = ()


PR_STEMS = frozenset(
    {
        "test_agent_native_recall_facade",
        "test_agent_last_recall_recovery",
        "test_agent_pull_gesture",
        "test_aippo_clause_lifecycle",
        "test_circuit_feedback",
        "test_cli_pulse",
        "test_cli_recovery_cards_core",
        "test_command_quoting_contract",
        "test_debt_report",
        "test_consolidation_priority",
        "test_dream_delivery_eligibility",
        "test_attention_route_compatibility",
        "test_first_useful_recall_demo",
        "test_health_human_text",
        "test_health_storage_pressure",
        "test_io_integrity",
        "test_lane_cache_verifier",
        "test_learning_loop_aippo_adapter",
        "test_learning_loop_behavioral_records",
        "test_learning_loop_effectiveness_ledger",
        "test_learning_loop_private_replay",
        "test_learning_loop_second_user_dogfood",
        "test_local_file_lock",
        "test_memory_system_incident_corpus",
        "test_microcircuit_router",
        "test_mcp_latest_reply",
        "test_mcp_search_memory_last_recall",
        "test_navigation_potential",
        "test_narrative_packet",
        "test_parallel_derivation_bundle",
        "test_prompt_hook_semantic_diagnostics",
        "test_prompt_hook_anti_nag_behavior",
        "test_prompt_hook_latency_status",
        "test_product_probe_helpers",
        "test_semantic_candidate_context_bridge_effectiveness",
        "test_semantic_result_cache",
        "test_semantic_subregion_budget",
        "test_search_quote_echo",
        "test_source_anchor_artifact_demotion",
        "test_source_io_kernel",
        "test_source_shape_projection",
    }
)

TEST_MODULE_STEMS = frozenset(
    {
        "test_aar_v2_action_time_nudges",
        "test_activation_payload_compaction",
        "test_activation_surface_authority",
        "test_active_recall",
        "test_active_recall_lock",
        "test_active_recall_lock_compaction",
        "test_active_path_packet",
        "test_action_hint_cache",
        "test_action_hint_hook",
        "test_action_hint_replay",
        "test_associative_path_inputs",
        "test_associative_path_feedback",
        "test_associative_path_source_shape",
        "test_associative_path_walker",
        "test_agency_affordance",
        "test_agency_host_timing",
        "test_agent_fallback_executor",
        "test_agent_fallback_materializer",
        "test_agent_discovery_release_check",
        "test_agent_feedback_macro_cli",
        "test_agent_background",
        "test_agent_deepen_compact_projection",
        "test_agent_last_recall_recovery",
        "test_agent_native_recall_facade",
        "test_agent_opt_in_aippo_semantic",
        "test_agent_opt_in_cli_contracts",
        "test_agent_opt_in_recall_routes",
        "test_agent_recall_apw_fallback",
        "test_agent_recall_compact_projection",
        "test_agent_pull_gesture",
        "test_agent_self_note_cli",
        "test_agent_self_notes",
        "test_agent_slop_guard",
        "test_aippo_clause_lifecycle",
        "test_aippo_feedback_eval_ficus",
        "test_aippo_skill_bridge",
        "test_aippo_working_contract",
        "test_aippocampus_cli",
        "test_aippocampus_health",
        "test_health_shell_commands",
        "test_aippocampus_lifecycle_hook",
        "test_aippocampus_maintenance",
        "test_aippocampus_mcp_server_catalog",
        "test_aippocampus_mcp_server_ops",
        "test_aippocampus_mcp_server_recall",
        "test_aippocampus_mcp_server_search_memory",
        "test_aippocampus_prompt_hook",
        "test_aippocampuslib",
        "test_ambient_recall_cards",
        "test_cli_recovery_cards",
        "test_cli_start",
        "test_codeql_workflow",
        "test_command_quoting_contract",
        "test_ambient_recall_policy",
        "test_ambient_source_reopen",
        "test_ambient_thread_cache",
        "test_attention_evidence_packager",
        "test_attention_hot_router",
        "test_attention_route_compatibility",
        "test_attention_route_tokens",
        "test_attention_router_contract",
        "test_architecture_boundaries",
        "test_avatar_posture",
        "test_avatar_illumination",
        "test_benchmark_attention_navigation_quality",
        "test_benchmark_associative_path_walker",
        "test_benchmark_attention_score_fusion_calibration",
        "test_benchmark_avatar_bounded_resonance",
        "test_benchmark_capability_provenance",
        "test_benchmark_coding_decision_shadow",
        "test_benchmark_amemgym",
        "test_benchmark_amemgym_official",
        "test_benchmark_agent_continuity_loop",
        "test_benchmark_entrypoints",
        "test_benchmark_family_promotion_candidates",
        "test_benchmark_cognitive_portrait",
        "test_benchmark_compaction_continuity",
        "test_benchmark_continuity_density_curve",
        "test_benchmark_continuous_memory_arms",
        "test_benchmark_codex_desktop_amemgym",
        "test_benchmark_corpus_converter",
        "test_benchmark_conversation_orientation_usefulness",
        "test_benchmark_conversational_media_ingest_recall",
        "test_benchmark_dream_delivery_quality",
        "test_benchmark_default_hook_recall_usefulness",
        "test_benchmark_diagnostic_meta_calibration",
        "test_benchmark_e2e50_behavior_live",
        "test_benchmark_e2e50_silent_constraint",
        "test_benchmark_episode_arc_sequence_usefulness",
        "test_benchmark_exact_source_search_flows",
        "test_benchmark_field_continuity",
        "test_benchmark_fresh_thread_recall_demo",
        "test_benchmark_graph_extraction_boundary",
        "test_benchmark_fts5_recall",
        "test_benchmark_hippocampal_hard_negatives",
        "test_benchmark_hippocampal_recall",
        "test_benchmark_knowledge_pollution",
        "test_benchmark_learning_loop_public_companion",
        "test_benchmark_live_semantic_gate",
        "test_benchmark_locomo_answer_usefulness",
        "test_benchmark_locomo_public_users",
        "test_benchmark_locomo_qa",
        "test_benchmark_longmemeval",
        "test_benchmark_longmemeval_answer",
        "test_benchmark_longmemeval_rerank_analysis",
        "test_benchmark_longmemeval_v2_context",
        "test_benchmark_longmemeval_v2_official_pilot",
        "test_benchmark_map_rot_lifecycle_debt",
        "test_benchmark_memory_decision_gate",
        "test_benchmark_memoryagentbench",
        "test_benchmark_maturity",
        "test_benchmark_multimodal_corpus_retrieval",
        "test_benchmark_multimodal_niah_evidence_pool",
        "test_benchmark_natural_handoff_usefulness",
        "test_benchmark_payload_fidelity",
        "test_benchmark_prompt_hot_path_funnel",
        "test_benchmark_provider_conformance",
        "test_benchmark_public_reliability_gauntlet",
        "test_benchmark_public_longitudinal_users",
        "test_benchmark_published_reports",
        "test_benchmark_question_aware_real_history",
        "test_benchmark_question_tracking_calibration",
        "test_benchmark_recall_degradation_audit",
        "test_benchmark_run_history_diff",
        "test_benchmark_segmented_merge_policy",
        "test_benchmark_semantic_robustness",
        "test_benchmark_source_evidence_retrieval",
        "test_benchmark_state_bench_agent_learning",
        "test_benchmark_state_dependent_preactivation",
        "test_benchmark_statistics",
        "test_benchmark_suite",
        "test_benchmark_vcs_future_event_recall",
        "test_benchmark_warm_ambient_recall",
        "test_benchmark_warm_ambient_sweep",
        "test_browser_memory_companion",
        "test_build_associations",
        "test_build_clean_source",
        "test_build_cognitive_map",
        "test_build_concept_graph",
        "test_concept_edge_utility",
        "test_consolidation_priority",
        "test_build_index",
        "test_build_project_timeline",
        "test_build_segments",
        "test_build_vcs_future_event_fixture",
        "test_capture_consolidation_boundary",
        "test_checkpoint",
        "test_changed_surface_preflight",
        "test_ci_parity",
        "test_cli_json_contract",
        "test_cli_pulse",
        "test_cli_recovery_cards_core",
        "test_cli_runtime_floor",
        "test_closeout_audit",
        "test_claude_code_hooks",
        "test_codex_long_session_smoke",
        "test_coding_decision_events",
        "test_coding_rejected_route_probes",
        "test_coding_ticket_host_contract",
        "test_episode_arc_private_adjudication",
        "test_episode_arc_route_producer",
        "test_episode_arcs",
        "test_compat_shim_inventory",
        "test_compensatory_dream",
        "test_continuity_domain_salience_adapter",
        "test_continuity_domain_producer",
        "test_continuity_domain_cli",
        "test_conversation_authority_and_armor",
        "test_continuity_domains",
        "test_coordination_topology",
        "test_task_orientation_packet",
        "test_telepathy_coordination_packet",
        "test_telepathy_handoff_store",
        "test_cross_agent_isolation",
        "test_correction_reconsolidation",
        "test_cognitive_load_sidecar",
        "test_cognitive_observatory",
        "test_cognitive_observatory_current_completeness",
        "test_cognitive_worker_mode",
        "test_circuit_feedback",
        "test_cross_agent_continuity_smoke",
        "test_debt_report",
        "test_deepseek_model_routing",
        "test_diagnose_hooks",
        "test_docs_health",
        "test_docs_health_benchmark_evidence",
        "test_docs_health_legacy_alias_inventory",
        "test_skill_entrypoint_docs",
        "test_dream_delivery_eligibility",
        "test_dream_atlas_pack",
        "test_dream_input_pack",
        "test_dream_lifecycle",
        "test_dream_live_shadow_ab",
        "test_dream_one_sidedness",
        "test_dream_precision_policy",
        "test_dream_queue",
        "test_dream_real_history_eval",
        "test_dream_retrospective_lifecycle",
        "test_dream_sleep_cycle",
        "test_dream_topology_scout",
        "test_dream_utility_telemetry",
        "test_dream_worker",
        "test_dream_working_memory",
        "test_dream_working_memory_compaction",
        "test_discussion_atlas_guard",
        "test_e2e50_seed_candidates",
        "test_encrypted_sync_bundle",
        "test_emergency_snapshot",
        "test_export_bundle",
        "test_fresh_thread_action_policy",
        "test_fresh_thread_activation_state",
        "test_fresh_thread_demo",
        "test_fresh_thread_real_history_smoke",
        "test_fresh_thread_scent_packet",
        "test_frontier_probe",
        "test_foreground_action_card",
        "test_foreground_issue_sweep",
        "test_foreground_recall_confidence",
        "test_first_useful_recall_demo",
        "test_foreground_usefulness_and_candidate_survival",
        "test_generic_jsonl_integration_smoke",
        "test_global_storage_defaults",
        "test_health_human_text",
        "test_health_operator_diagnostics",
        "test_health_storage_pressure",
        "test_hook_agent_affordance",
        "test_import_bundle",
        "test_import_coupling",
        "test_install_lifecycle_hook",
        "test_install_action_hint_hook",
        "test_install_prompt_hook",
        "test_io_integrity",
        "test_issue_work_guard",
        "test_known_artifact_recall_dogfood",
        "test_lane_cache_verifier",
        "test_journey_tracking",
        "test_knowledge_answer_gate",
        "test_knowledge_capability_conflicts",
        "test_knowledge_capability_manifest",
        "test_knowledge_source_schema",
        "test_knowledge_runtime_boundary",
        "test_legacy_aliases",
        "test_life_wide_registry_smoke",
        "test_learning_loop_aippo_adapter",
        "test_learning_loop_behavioral_records",
        "test_learning_loop_effectiveness_ledger",
        "test_learning_loop_private_replay",
        "test_learning_loop_second_user_dogfood",
        "test_living_cue_cache",
        "test_local_global_compatibility",
        "test_log_retention",
        "test_long_thread_segment_soak",
        "test_magic_activation_policy",
        "test_map_rot_maintenance",
        "test_macro_agent_packets",
        "test_macro_field_atlas",
        "test_macro_field_live",
        "test_macro_group_action_invariants",
        "test_macro_hexagram",
        "test_macro_line_topology",
        "test_macro_momentum",
        "test_macro_orientation_state",
        "test_macro_perturbation",
        "test_macro_router_interface",
        "test_macro_stage_tracker",
        "test_macro_three_powers",
        "test_macro_timing_affordance",
        "test_macro_timing_recheck_experiment",
        "test_macro_topology_loadbearing",
        "test_macro_total_encoder",
        "test_memory_evidence_drawer",
        "test_macos_install_smoke_workflow",
        "test_memory_candidate_router",
        "test_microcircuit_router",
        "test_memory_pain_prompt_hook_smoke",
        "test_memory_system_incident_corpus",
        "test_mcp_default_clean_source_resolution",
        "test_mcp_compact_boundaries",
        "test_mcp_memory_health_recovery",
        "test_mcp_protocol_conformance",
        "test_mcp_search_memory_last_recall",
        "test_mcp_latest_reply",
        "test_model_client",
        "test_multilingual_prompt_hook_smoke",
        "test_multimodal_answer_gate",
        "test_multimodal_provider_routing",
        "test_multimodal_source_manifest",
        "test_mutation_smoke",
        "test_navigation_data_quality_guard",
        "test_navigation_potential",
        "test_narrative_packet",
        "test_near_user_semantic_classifier_audit",
        "test_object_storage_sync",
        "test_onboard_codex",
        "test_openai_agents_sdk_smoke",
        "test_operation_claim_gate",
        "test_operation_integrity",
        "test_package_windows_binary",
        "test_packet_topology_diagnostic",
        "test_parallel_derivation_bundle",
        "test_path_identity",
        "test_planning_audit",
        "test_plugin_distribution",
        "test_plugin_installer",
        "test_posture_relation_policy",
        "test_prewarm_planner",
        "test_project_triage",
        "test_privacy_projection",
        "test_prompt_context_render",
        "test_prompt_foreground_budget",
        "test_prompt_hot_path_funnel",
        "test_prompt_hook_ambient_cache",
        "test_prompt_hook_anti_nag_behavior",
        "test_prompt_hook_dream_delivery",
        "test_prompt_hook_hot_path",
        "test_prompt_hook_latency_status",
        "test_product_probe_helpers",
        "test_prompt_hook_routing_scent",
        "test_prompt_hook_semantic_evidence",
        "test_prompt_hook_semantic_gate",
        "test_prompt_hook_semantic_diagnostics",
        "test_prompt_hook_source_routes",
        "test_prompt_hook_telemetry_audit",
        "test_prompt_hook_working_memory",
        "test_prompt_loader_cache",
        "test_prompt_recall_decision_boundaries",
        "test_prompt_recall_policy",
        "test_prompt_recall_threshold",
        "test_provider_doctor",
        "test_provider_key_bridge",
        "test_public_boundary_check",
        "test_public_output",
        "test_public_handoff_hygiene",
        "test_question_confirmation_live",
        "test_question_confirmation_live_smoke",
        "test_question_feedback_policy",
        "test_question_health",
        "test_question_index_sidecar",
        "test_question_prefilter_parity",
        "test_question_resolution",
        "test_question_tracking",
        "test_question_tracking_scale_smoke",
        "test_question_vector_index",
        "test_query_pattern_enrichment",
        "test_query_pattern_routes_prompt_hook",
        "test_query_profile",
        "test_recall_funnel_smoke",
        "test_recall_feedback_events",
        "test_recall_integration_readiness",
        "test_recall_navigation_comparison",
        "test_recall_navigation_promotion",
        "test_recall_owner_guard",
        "test_recall_scoring_policy",
        "test_recall_structure_time_features",
        "test_recall_why_diagnostics",
        "test_relationship_origin_recall",
        "test_reflection_space",
        "test_registry_register_rollout",
        "test_registry_search",
        "test_registry_store",
        "test_repo_familiarity",
        "test_repo_familiarity_foreground_experiment",
        "test_retrieval_query_policy",
        "test_retrieval_lifecycle",
        "test_retrieval_reconsolidation_consumer",
        "test_retrieval_score_fusion",
        "test_routing_boundaries",
        "test_runtime_recheck_events",
        "test_runtime_contracts_and_config_registry",
        "test_run_tests_tiers",
        "test_schema_profiles",
        "test_search_clean_source",
        "test_search_clean_source_foreground_projection",
        "test_search_quote_echo",
        "test_last_recall_source_search",
        "test_local_file_lock",
        "test_search_decision_adapter",
        "test_search_segments",
        "test_source_joined_routing_decision",
        "test_semantic_cue_cache",
        "test_semantic_candidate_context_bridge_effectiveness",
        "test_semantic_paraphrase_reuse_smoke",
        "test_semantic_recall_gate",
        "test_semantic_result_cache",
        "test_semantic_scope_labels",
        "test_semantic_scope_real_history_smoke",
        "test_semantic_scope_source_review",
        "test_semantic_scope_suppressed_recovery",
        "test_semantic_subregion_budget",
        "test_semantic_trigger_compaction",
        "test_semantic_trigger_router",
        "test_semantic_warm_route_producer",
        "test_simulate_prompt_hook",
        "test_spend_doctor",
        "test_source_shape_runtime",
        "test_source_shape_projection",
        "test_source_anchor_artifact_demotion",
        "test_source_evidence_recall_eval",
        "test_source_factual_aliases",
        "test_source_intake_health",
        "test_source_io_kernel",
        "test_source_semantic_candidate_recall_eval",
        "test_source_backed_lessons",
        "test_learning_loop",
        "test_source_reopen_budget",
        "test_source_texture",
        "test_sparse_provenance_codebook",
        "test_stage_0_5_smoke",
        "test_standard_line_reranker_contract",
        "test_storage_capacity_report",
        "test_storage_governance",
        "test_successor_evidence",
        "test_subconscious_agent",
        "test_subconscious_event_salience_gate",
        "test_subconscious_jobs_core",
        "test_subconscious_jobs_questions",
        "test_subconscious_jobs_runner",
        "test_subconscious_review",
        "test_subconscious_scheduler",
        "test_subconscious_staging_maintenance",
        "test_subconscious_worker",
        "test_sync_bundle",
        "test_synthetic_scale_capacity_smoke",
        "test_test_plan",
        "test_theme_emergence",
        "test_thread_story_packet",
        "test_time_driven_maintenance",
        "test_topology_anchor_policy",
        "test_update_agent_status",
        "test_update_foreground_actions",
        "test_update_sync",
        "test_uninstall_inventory",
        "test_vault_dashboard_assets",
        "test_warm_ambient_privacy_policy",
        "test_warm_ambient_recall",
        "test_warm_ambient_scheduler_policy",
        "test_warm_ambient_topic_epoch_policy",
        "test_wheel_contract_release",
        "test_worker_hook_handoff_smoke",
        "test_yi_macro_runtime_interfaces",
    }
)

QUICK_STEMS = frozenset(
    {
        "test_active_path_packet",
        "test_action_hint_replay",
        "test_agent_fallback_executor",
        "test_agent_fallback_materializer",
        "test_aippo_clause_lifecycle",
        "test_aippo_feedback_eval_ficus",
        "test_aippocampuslib",
        "test_capture_consolidation_boundary",
        "test_ci_parity",
        "test_cli_json_contract",
        "test_cognitive_observatory_current_completeness",
        "test_circuit_feedback",
        "test_episode_arc_route_producer",
        "test_concept_edge_utility",
        "test_continuity_domain_salience_adapter",
        "test_continuity_domain_producer",
        "test_cross_agent_isolation",
        "test_foreground_usefulness_and_candidate_survival",
        "test_magic_activation_policy",
        "test_memory_evidence_drawer",
        "test_microcircuit_router",
        "test_path_identity",
        "test_prewarm_planner",
        "test_prompt_context_render",
        "test_privacy_projection",
        "test_public_output",
        "test_query_pattern_routes_prompt_hook",
        "test_query_profile",
        "test_recall_feedback_events",
        "test_runtime_recheck_events",
        "test_semantic_subregion_budget",
        "test_semantic_warm_route_producer",
        "test_source_shape_projection",
        "test_source_shape_runtime",
        "test_source_factual_aliases",
        "test_source_intake_health",
        "test_source_backed_lessons",
        "test_learning_loop_aippo_adapter",
        "test_learning_loop_behavioral_records",
        "test_learning_loop_effectiveness_ledger",
        "test_learning_loop_private_replay",
        "test_learning_loop_second_user_dogfood",
        "test_source_reopen_budget",
        "test_source_texture",
        "test_standard_line_reranker_contract",
        "test_topology_anchor_policy",
    }
)

SMOKE_STEMS = frozenset(
    {
        "test_aippocampus_lifecycle_hook",
        "test_action_hint_hook",
        "test_codex_long_session_smoke",
        "test_claude_code_hooks",
        "test_cross_agent_continuity_smoke",
        "test_diagnose_hooks",
        "test_e2e50_seed_candidates",
        "test_fresh_thread_real_history_smoke",
        "test_frontier_probe",
        "test_generic_jsonl_integration_smoke",
        "test_hook_agent_affordance",
        "test_install_action_hint_hook",
        "test_install_lifecycle_hook",
        "test_install_prompt_hook",
        "test_known_artifact_recall_dogfood",
        "test_long_thread_segment_soak",
        "test_macos_install_smoke_workflow",
        "test_memory_pain_prompt_hook_smoke",
        "test_multilingual_prompt_hook_smoke",
        "test_openai_agents_sdk_smoke",
        "test_question_confirmation_live_smoke",
        "test_question_tracking_scale_smoke",
        "test_recall_funnel_smoke",
        "test_semantic_paraphrase_reuse_smoke",
        "test_simulate_prompt_hook",
        "test_synthetic_scale_capacity_smoke",
        "test_worker_hook_handoff_smoke",
        "test_wheel_contract_release",
    }
)

INTEGRATION_STEMS = frozenset(
    {
        "test_aippocampus_mcp_server_catalog",
        "test_aippocampus_mcp_server_ops",
        "test_aippocampus_mcp_server_recall",
        "test_aippocampus_mcp_server_search_memory",
        "test_browser_memory_companion",
        "test_deepseek_model_routing",
        "test_dream_live_shadow_ab",
        "test_encrypted_sync_bundle",
        "test_export_bundle",
        "test_import_bundle",
        "test_cognitive_worker_mode",
        "test_model_client",
        "test_mcp_default_clean_source_resolution",
        "test_mcp_memory_health_recovery",
        "test_mcp_protocol_conformance",
        "test_mcp_search_memory_last_recall",
        "test_multimodal_provider_routing",
        "test_package_windows_binary",
        "test_project_triage",
        "test_provider_doctor",
        "test_question_confirmation_live",
        "test_relationship_origin_recall",
        "test_sync_bundle",
    }
)

SLOW_STEMS = frozenset(
    {
        "test_aippocampus_prompt_hook",
        "test_dream_real_history_eval",
        "test_life_wide_registry_smoke",
        "test_object_storage_sync",
        "test_onboard_codex",
        "test_plugin_distribution",
        "test_prompt_hook_ambient_cache",
        "test_prompt_hook_dream_delivery",
        "test_prompt_hook_routing_scent",
        "test_prompt_hook_semantic_evidence",
        "test_prompt_hook_semantic_gate",
        "test_prompt_hook_source_routes",
        "test_prompt_hook_telemetry_audit",
        "test_prompt_hook_working_memory",
        "test_semantic_scope_real_history_smoke",
        "test_stage_0_5_smoke",
    }
)

BENCHMARK_STEMS = frozenset(
    {
        "test_benchmark_coding_decision_shadow",
        "test_benchmark_amemgym",
        "test_benchmark_amemgym_official",
        "test_benchmark_agent_continuity_loop",
        "test_benchmark_associative_path_walker",
        "test_benchmark_attention_navigation_quality",
        "test_benchmark_attention_score_fusion_calibration",
        "test_benchmark_avatar_bounded_resonance",
        "test_benchmark_entrypoints",
        "test_benchmark_family_promotion_candidates",
        "test_benchmark_cognitive_portrait",
        "test_benchmark_compaction_continuity",
        "test_benchmark_continuity_density_curve",
        "test_benchmark_continuous_memory_arms",
        "test_benchmark_codex_desktop_amemgym",
        "test_benchmark_conversation_orientation_usefulness",
        "test_benchmark_conversational_media_ingest_recall",
        "test_benchmark_dream_delivery_quality",
        "test_benchmark_default_hook_recall_usefulness",
        "test_benchmark_diagnostic_meta_calibration",
        "test_benchmark_e2e50_behavior_live",
        "test_benchmark_e2e50_silent_constraint",
        "test_benchmark_episode_arc_sequence_usefulness",
        "test_benchmark_exact_source_search_flows",
        "test_benchmark_field_continuity",
        "test_benchmark_fresh_thread_recall_demo",
        "test_benchmark_fts5_recall",
        "test_benchmark_hippocampal_hard_negatives",
        "test_benchmark_hippocampal_recall",
        "test_benchmark_knowledge_pollution",
        "test_benchmark_learning_loop_public_companion",
        "test_benchmark_live_semantic_gate",
        "test_benchmark_locomo_answer_usefulness",
        "test_benchmark_locomo_public_users",
        "test_benchmark_locomo_qa",
        "test_benchmark_longmemeval",
        "test_benchmark_longmemeval_answer",
        "test_benchmark_longmemeval_rerank_analysis",
        "test_benchmark_longmemeval_v2_context",
        "test_benchmark_longmemeval_v2_official_pilot",
        "test_benchmark_map_rot_lifecycle_debt",
        "test_benchmark_memory_decision_gate",
        "test_benchmark_memoryagentbench",
        "test_benchmark_maturity",
        "test_benchmark_multimodal_corpus_retrieval",
        "test_benchmark_multimodal_niah_evidence_pool",
        "test_benchmark_natural_handoff_usefulness",
        "test_benchmark_payload_fidelity",
        "test_benchmark_prompt_hot_path_funnel",
        "test_benchmark_provider_conformance",
        "test_benchmark_public_reliability_gauntlet",
        "test_benchmark_public_longitudinal_users",
        "test_benchmark_published_reports",
        "test_benchmark_question_aware_real_history",
        "test_benchmark_question_tracking_calibration",
        "test_benchmark_recall_degradation_audit",
        "test_benchmark_run_history_diff",
        "test_benchmark_segmented_merge_policy",
        "test_benchmark_semantic_robustness",
        "test_benchmark_source_evidence_retrieval",
        "test_benchmark_state_bench_agent_learning",
        "test_benchmark_state_dependent_preactivation",
        "test_benchmark_statistics",
        "test_benchmark_suite",
        "test_benchmark_vcs_future_event_recall",
        "test_benchmark_warm_ambient_recall",
        "test_benchmark_warm_ambient_sweep",
    }
)

BENCHMARK_SMOKE_STEMS = frozenset(
    {
        "test_benchmark_field_continuity",
        "test_benchmark_amemgym",
        "test_benchmark_amemgym_official",
        "test_benchmark_agent_continuity_loop",
        "test_benchmark_associative_path_walker",
        "test_benchmark_attention_navigation_quality",
        "test_benchmark_attention_score_fusion_calibration",
        "test_benchmark_avatar_bounded_resonance",
        "test_benchmark_codex_desktop_amemgym",
        "test_benchmark_continuity_density_curve",
        "test_benchmark_conversation_orientation_usefulness",
        "test_benchmark_entrypoints",
        "test_benchmark_family_promotion_candidates",
        "test_benchmark_dream_delivery_quality",
        "test_benchmark_default_hook_recall_usefulness",
        "test_benchmark_diagnostic_meta_calibration",
        "test_benchmark_e2e50_behavior_live",
        "test_benchmark_e2e50_silent_constraint",
        "test_benchmark_exact_source_search_flows",
        "test_benchmark_hippocampal_recall",
        "test_benchmark_knowledge_pollution",
        "test_benchmark_learning_loop_public_companion",
        "test_benchmark_locomo_public_users",
        "test_benchmark_locomo_qa",
        "test_benchmark_longmemeval_answer",
        "test_benchmark_longmemeval_v2_context",
        "test_benchmark_longmemeval_v2_official_pilot",
        "test_benchmark_longmemeval_rerank_analysis",
        "test_benchmark_map_rot_lifecycle_debt",
        "test_benchmark_maturity",
        "test_benchmark_memoryagentbench",
        "test_benchmark_natural_handoff_usefulness",
        "test_benchmark_provider_conformance",
        "test_benchmark_public_reliability_gauntlet",
        "test_benchmark_public_longitudinal_users",
        "test_benchmark_published_reports",
        "test_benchmark_recall_degradation_audit",
        "test_benchmark_segmented_merge_policy",
        "test_benchmark_state_bench_agent_learning",
        "test_benchmark_state_dependent_preactivation",
        "test_benchmark_statistics",
        "test_benchmark_suite",
        "test_benchmark_vcs_future_event_recall",
        "test_e2e50_seed_candidates",
    }
)

TAG_OVERRIDES = {
    "test_aippocampus_mcp_server_catalog": ("mcp",),
    "test_aippocampus_mcp_server_ops": ("mcp", "subprocess", "sync", "health"),
    "test_aippocampus_mcp_server_recall": ("mcp", "recall", "registry"),
    "test_aippocampus_mcp_server_search_memory": ("mcp", "registry", "source_open"),
    "test_agent_slop_guard": ("agent_guard", "tooling"),
    "test_changed_surface_preflight": ("tooling", "test_runner"),
    "test_browser_memory_companion": ("browser",),
    "test_codex_long_session_smoke": ("host", "filesystem"),
    "test_claude_code_hooks": ("hook", "subprocess", "claude-code"),
    "test_cli_pulse": ("cli", "foreground_behavior"),
    "test_codeql_workflow": ("ci", "github", "workflow"),
    "test_command_quoting_contract": ("cli", "security", "quoting"),
    "test_cognitive_worker_mode": ("provider",),
    "test_cross_agent_continuity_smoke": ("cross_agent", "host"),
    "test_deepseek_model_routing": ("provider",),
    "test_diagnose_hooks": ("hook", "subprocess"),
    "test_dream_lifecycle": ("dream", "lifecycle", "foreground_behavior"),
    "test_dream_live_shadow_ab": ("host",),
    "test_benchmark_e2e50_behavior_live": ("benchmark", "model-backed", "public_fixture"),
    "test_e2e50_seed_candidates": ("benchmark", "public_fixture"),
    "test_encrypted_sync_bundle": ("sync", "filesystem"),
    "test_export_bundle": ("filesystem",),
    "test_first_useful_recall_demo": ("docs", "public_fixture", "recall"),
    "test_import_bundle": ("filesystem",),
    "test_install_lifecycle_hook": ("install", "hook"),
    "test_install_prompt_hook": ("install", "hook"),
    "test_io_integrity": ("filesystem", "io"),
    "test_learning_loop_behavioral_records": ("learning_loop", "privacy", "filesystem"),
    "test_prompt_foreground_budget": ("hook",),
    "test_prompt_hook_anti_nag_behavior": ("anti_nag", "foreground_behavior", "hook_behavior"),
    "test_ambient_recall_policy": ("hook_behavior", "foreground_behavior"),
    "test_prompt_hook_hot_path": ("hook_behavior", "foreground_behavior"),
    "test_prompt_hook_latency_status": ("hook", "install", "foreground_behavior"),
    "test_prompt_hook_semantic_diagnostics": ("hook", "semantic"),
    "test_privacy_projection": ("privacy",),
    "test_public_boundary_check": ("release", "privacy"),
    "test_relationship_origin_recall": ("cli", "mcp", "recall", "registry"),
    "test_search_quote_echo": ("search", "source_open", "real_history"),
    "test_skill_entrypoint_docs": ("docs", "skill_surface"),
    "test_benchmark_avatar_bounded_resonance": ("benchmark", "public_fixture"),
    "test_benchmark_provider_conformance": ("provider", "mcp", "public_fixture"),
    "test_benchmark_entrypoints": ("benchmark", "entrypoint", "subprocess"),
    "test_life_wide_registry_smoke": ("smoke", "registry", "slow"),
    "test_local_file_lock": ("filesystem", "lock_owner"),
    "test_macos_install_smoke_workflow": ("install", "macos"),
    "test_model_client": ("provider",),
    "test_mcp_compact_boundaries": ("mcp", "foreground_behavior"),
    "test_mcp_default_clean_source_resolution": ("mcp", "recall"),
    "test_mcp_memory_health_recovery": ("mcp",),
    "test_mcp_protocol_conformance": ("mcp", "protocol", "source_open"),
    "test_mcp_search_memory_last_recall": ("mcp", "recall", "source_open"),
    "test_multimodal_provider_routing": ("provider", "multimodal"),
    "test_mutation_smoke": ("mutation_smoke", "tooling"),
    "test_object_storage_sync": ("sync", "provider", "slow"),
    "test_onboard_codex": ("install", "onboarding", "slow"),
    "test_openai_agents_sdk_smoke": ("provider", "optional_dependency"),
    "test_package_windows_binary": ("windows", "packaging"),
    "test_plugin_distribution": ("packaging", "release", "slow"),
    "test_project_triage": ("github",),
    "test_provider_doctor": ("provider",),
    "test_foreground_issue_sweep": ("foreground_behavior", "runtime", "docs"),
    "test_provider_key_bridge": ("hook", "install", "provider"),
    "test_prompt_loader_cache": ("filesystem", "performance"),
    "test_question_confirmation_live": ("live_contract",),
    "test_recall_owner_guard": ("docs", "architecture_guard", "recall"),
    "test_semantic_result_cache": ("semantic", "cache", "lock_owner"),
    "test_semantic_scope_real_history_smoke": ("real_history", "slow"),
    "test_simulate_prompt_hook": ("hook",),
    "test_stage_0_5_smoke": ("release", "slow"),
    "test_sync_bundle": ("sync", "filesystem"),
    "test_update_agent_status": ("install", "packaging"),
    "test_update_foreground_actions": ("install", "hook", "packaging"),
    "test_update_sync": ("install", "filesystem", "hook", "packaging"),
    "test_uninstall_inventory": ("filesystem", "install", "privacy"),
    "test_wheel_contract_release": ("release", "packaging"),
    "test_worker_hook_handoff_smoke": ("smoke", "hook", "warm"),
}


def _module_name(stem: str) -> str:
    return f"tests.aippocampus.{stem}"


ALL_TEST_MODULES = frozenset(_module_name(stem) for stem in TEST_MODULE_STEMS)
QUICK_MODULES = frozenset(_module_name(stem) for stem in QUICK_STEMS)
SMOKE_MODULES = frozenset(_module_name(stem) for stem in SMOKE_STEMS)
INTEGRATION_MODULES = frozenset(_module_name(stem) for stem in INTEGRATION_STEMS)
SLOW_MODULES = frozenset(_module_name(stem) for stem in SLOW_STEMS)
BENCHMARK_MODULES = frozenset(_module_name(stem) for stem in BENCHMARK_STEMS)
BENCHMARK_SMOKE_MODULES = frozenset(_module_name(stem) for stem in BENCHMARK_SMOKE_STEMS)

TIER_SHRINK_REPLACEMENT_LANES: dict[str, dict[str, str]] = {
    _module_name("test_cli_recovery_cards"): {
        "primary_tier": "broad",
        "replacement_lane": (
            "tests.aippocampus.test_cli_recovery_cards_core remains in pr; "
            "broad-pr and focused CLI recovery-card runs own the full catalog."
        ),
        "rationale": (
            "The full recovery-card catalog is valuable but too wide for every "
            "local PR loop; the PR core keeps representative foreground-action "
            "and no-traceback contracts in the default lane."
        ),
    },
    _module_name("test_benchmark_capability_provenance"): {
        "primary_tier": "benchmark",
        "replacement_lane": "benchmark-smoke public-fast and benchmark tiers",
        "rationale": (
            "Benchmark capability provenance is benchmark infrastructure evidence, "
            "not ordinary PR product safety."
        ),
    },
    _module_name("test_benchmark_default_hook_recall_usefulness"): {
        "primary_tier": "benchmark",
        "replacement_lane": "benchmark-smoke public-fast and benchmark tiers",
        "rationale": (
            "Default-hook recall usefulness belongs to benchmark evidence lanes; "
            "runtime hook changes still get focused planner commands."
        ),
    },
    _module_name("test_benchmark_dream_delivery_quality"): {
        "primary_tier": "benchmark",
        "replacement_lane": "benchmark-smoke public-fast and benchmark tiers",
        "rationale": (
            "Dream-delivery benchmark wiring should stay measurable without "
            "making benchmark-shaped evidence a default PR ritual."
        ),
    },
    _module_name("test_benchmark_entrypoints"): {
        "primary_tier": "benchmark",
        "replacement_lane": "benchmark-smoke public-fast and benchmark tiers",
        "rationale": (
            "Benchmark subprocess entrypoints are still covered by benchmark-smoke; "
            "they do not need to run in quick for unrelated edits."
        ),
    },
    _module_name("test_benchmark_episode_arc_sequence_usefulness"): {
        "primary_tier": "benchmark",
        "replacement_lane": "benchmark-smoke public-fast and benchmark tiers",
        "rationale": (
            "Episode-arc usefulness is benchmark-scope evidence, while runtime "
            "episode changes are covered by focused tests and broad-pr."
        ),
    },
    _module_name("test_benchmark_graph_extraction_boundary"): {
        "primary_tier": "benchmark",
        "replacement_lane": "benchmark and broad-pr architecture boundary coverage",
        "rationale": (
            "Graph extraction is an architecture boundary guard; keeping it out "
            "of pr prevents benchmark-shaped guards from silently growing the "
            "default lane."
        ),
    },
}

FAST_LANE_RECLASSIFIED_MODULES: dict[str, tuple[str, str, str]] = {
    "test_agent_slop_guard": (
        "broad",
        "broad-pr plus focused agent-slop guard tests own rule changes; the changed-surface planner still runs the guard on touched Python files.",
        "Agent-slop fixtures are prevention tooling, not a module every unrelated local PR should pay for.",
    ),
    "test_docs_health_benchmark_evidence": (
        "broad",
        "broad-pr plus focused docs-health benchmark-evidence runs own docs/evidence edits.",
        "Benchmark-evidence documentation checks should not make the default PR lane look like a benchmark closeout lane.",
    ),
    "test_macro_topology_loadbearing": (
        "broad",
        "broad-pr plus focused macro-topology runs own macro topology changes.",
        "Macro topology coverage is product-specific breadth rather than default PR-critical infrastructure.",
    ),
    "test_macro_total_encoder": (
        "broad",
        "broad-pr plus focused macro-total encoder runs own macro encoder changes.",
        "Macro encoder semantics should be selected by changed surface instead of every unrelated PR.",
    ),
    "test_navigation_data_quality_guard": (
        "broad",
        "broad-pr plus focused navigation-data-quality guard runs own association/concept-graph edits.",
        "The advisory navigation quality guard is essential when navigation surfaces change but too specialized for every local PR loop.",
    ),
    "test_update_agent_status": (
        "broad",
        "broad-pr plus focused update-agent-status runs own installer/update status edits.",
        "Install/status reporting is pre-merge safety and focused changed-surface coverage, not an always-on PR module.",
    ),
    "test_active_recall": (
        "broad",
        "broad-pr plus focused active-recall runs own the full matrix.",
        "Active recall behavior is important, but the full matrix is wider than the inner loop.",
    ),
    "test_active_recall_lock": (
        "broad",
        "broad-pr plus focused active-recall lock runs own lock and cache edge cases.",
        "Lock/cache edge cases belong to broad deterministic coverage unless the changed surface asks for them.",
    ),
    "test_action_hint_cache": (
        "broad",
        "broad-pr plus focused action-hint cache runs own the full cache contract.",
        "Action-hint cache breadth is not required for every unrelated quick run.",
    ),
    "test_action_hint_hook": (
        "smoke",
        "smoke and broad-pr own hook behavior; hook changes get focused tests from the planner.",
        "Hook surfaces are host-adjacent and should not live in quick by default.",
    ),
    "test_architecture_boundaries": (
        "broad",
        "broad-pr and architecture changed-surface planner commands own the boundary suite.",
        "Architecture boundary coverage is pre-merge safety, not ordinary inner-loop iteration.",
    ),
    "test_build_clean_source": (
        "broad",
        "broad-pr plus focused clean-source build runs own source-building breadth.",
        "Clean-source construction has enough fixture breadth to stay out of quick by default.",
    ),
    "test_foreground_action_card": (
        "broad",
        "broad-pr plus focused foreground-action contract runs own the full card matrix.",
        "PR keeps smaller command/quoting and anti-nag contracts; the full card catalog is wider.",
    ),
    "test_hook_agent_affordance": (
        "smoke",
        "smoke and broad-pr own hook affordance wiring; #2554 uses focused hook tests.",
        "Ambient hook affordances are a foreground smoke surface, not quick default coverage.",
    ),
    "test_issue_work_guard": (
        "broad",
        "broad-pr plus focused issue-work guard runs own contributor workflow protection.",
        "Issue workflow checks are valuable but not a quick inner-loop dependency.",
    ),
    "test_retrieval_lifecycle": (
        "broad",
        "broad-pr plus focused retrieval-lifecycle runs own lifecycle breadth.",
        "Lifecycle breadth should be selected by changed surface, not every quick run.",
    ),
    "test_runtime_contracts_and_config_registry": (
        "broad",
        "broad-pr plus focused runtime/config contract runs own registry-wide contract checks.",
        "Runtime registry coverage is broad deterministic safety rather than quick default.",
    ),
    "test_run_tests_tiers": (
        "broad",
        "broad-pr plus focused run-tests tier checks own runner manifest changes.",
        "The runner tests are essential when tier files change, but too wide for every quick run.",
    ),
    "test_last_recall_source_search": (
        "broad",
        "broad-pr plus focused last-recall source-search runs own recall source breadth.",
        "Last-recall source-search coverage belongs with recall changed-surface checks.",
    ),
    "test_task_orientation_packet": (
        "broad",
        "broad-pr plus focused task-orientation runs own packet projection breadth.",
        "Orientation packet coverage is broad enough to stay out of quick by default.",
    ),
    "test_learning_loop": (
        "broad",
        "broad-pr plus focused learning-loop runs own the full loop contract.",
        "PR keeps selected learning-loop slices; the whole loop is broad deterministic coverage.",
    ),
    "test_sparse_provenance_codebook": (
        "broad",
        "broad-pr plus focused provenance codebook runs own sparse-provenance breadth.",
        "Provenance-codebook checks are evidence hygiene, not inner-loop coverage.",
    ),
    "test_test_plan": (
        "broad",
        "broad-pr plus focused test-plan runs own planner changes.",
        "Planner behavior should be tested when touched, not by every quick run.",
    ),
    "test_agent_feedback_macro_cli": (
        "broad",
        "broad-pr plus focused agent feedback macro CLI runs own CLI breadth.",
        "Macro feedback CLI coverage is broader than the PR-critical core.",
    ),
    "test_agent_background": (
        "broad",
        "broad-pr plus focused agent-background runs own compact/detail projection breadth.",
        "Background projection changed-surface tests remain explicit without bloating every PR gate.",
    ),
    "test_agent_opt_in_aippo_semantic": (
        "broad",
        "broad-pr plus focused AIppo semantic opt-in runs own semantic breadth.",
        "Semantic opt-in coverage is important but not fast-lane default coverage.",
    ),
    "test_agent_opt_in_cli_contracts": (
        "broad",
        "broad-pr plus focused opt-in CLI contract runs own CLI breadth.",
        "PR keeps smaller command/quoting contracts; the opt-in CLI matrix is broad.",
    ),
    "test_agent_opt_in_recall_routes": (
        "broad",
        "broad-pr plus focused recall-route runs own the full route matrix.",
        "Recall route matrix tests are selected by recall changed-surface work.",
    ),
    "test_agent_recall_apw_fallback": (
        "broad",
        "broad-pr plus focused APW fallback runs own APW recovery breadth.",
        "APW fallback is actively guarded by focused changed-surface tests and broad-pr.",
    ),
    "test_agent_recall_compact_projection": (
        "broad",
        "broad-pr plus focused compact recall projection runs own projection breadth.",
        "Compact recall projection has many route families; changed surfaces should call it directly.",
    ),
    "test_agent_self_note_cli": (
        "broad",
        "broad-pr plus focused self-note CLI runs own CLI breadth.",
        "Self-note CLI coverage is not PR-critical for unrelated changes.",
    ),
    "test_agent_self_notes": (
        "broad",
        "broad-pr plus focused agent-self-notes runs own source-note breadth.",
        "Self-note source behavior belongs to changed-surface coverage and broad-pr.",
    ),
    "test_aippo_skill_bridge": (
        "broad",
        "broad-pr plus focused AIppo skill bridge runs own bridge breadth.",
        "Skill bridge checks are valuable but broader than the local PR gate.",
    ),
    "test_aippo_working_contract": (
        "broad",
        "broad-pr plus focused AIppo working-contract runs own full contract breadth.",
        "Working-contract breadth is not needed for every local PR run.",
    ),
    "test_ambient_recall_cards": (
        "broad",
        "broad-pr plus focused ambient recall card runs own the full card matrix.",
        "Ambient recall cards are a wide foreground projection surface.",
    ),
    "test_avatar_illumination": (
        "broad",
        "broad-pr plus focused avatar illumination runs own avatar behavior breadth.",
        "Avatar behavior is product coverage, not fast-lane default coverage.",
    ),
    "test_cognitive_load_sidecar": (
        "broad",
        "broad-pr plus focused cognitive-load sidecar runs own sidecar breadth.",
        "Cognitive-load sidecar coverage should follow changed-surface selection.",
    ),
    "test_cognitive_observatory": (
        "broad",
        "broad-pr plus focused cognitive observatory runs own observatory breadth.",
        "Observatory coverage is broad diagnostic safety, not a default PR chore.",
    ),
    "test_cli_start": (
        "broad",
        "broad-pr plus focused CLI start runs own onboarding/start breadth.",
        "Start-card breadth is selected by CLI/onboarding changes.",
    ),
    "test_continuity_domain_cli": (
        "broad",
        "broad-pr plus focused continuity-domain CLI runs own CLI breadth.",
        "Continuity-domain CLI tests are broader than the default PR gate.",
    ),
    "test_local_global_compatibility": (
        "broad",
        "broad-pr plus focused local/global compatibility runs own route-quality breadth.",
        "Compatibility route matrices should not keep PR one module over budget.",
    ),
    "test_query_pattern_enrichment": (
        "broad",
        "broad-pr plus focused query-pattern enrichment runs own enrichment breadth.",
        "Query-pattern breadth is selected by retrieval/query changes.",
    ),
    "test_question_tracking": (
        "broad",
        "broad-pr plus focused question-tracking runs own question breadth.",
        "Question-tracking breadth is useful but not default PR coverage.",
    ),
    "test_successor_evidence": (
        "broad",
        "broad-pr plus focused successor-evidence runs own evidence breadth.",
        "Successor evidence checks belong to broad deterministic evidence coverage.",
    ),
    "test_yi_macro_runtime_interfaces": (
        "broad",
        "broad-pr plus focused Yi macro runtime interface runs own macro breadth.",
        "Macro runtime interface breadth is not required for every local PR gate.",
    ),
}

TIER_SHRINK_REPLACEMENT_LANES.update(
    {
        _module_name(stem): {
            "primary_tier": primary_tier,
            "replacement_lane": replacement_lane,
            "rationale": rationale,
        }
        for stem, (primary_tier, replacement_lane, rationale) in FAST_LANE_RECLASSIFIED_MODULES.items()
    }
)

TIER_ALIASES: dict[str, str] = {}
PR_PRIMARY_TIERS = frozenset({"quick", "pr"})
BROAD_PR_PRIMARY_TIERS = frozenset({"quick", "pr", "broad", "smoke", "integration"})
PRIMARY_TIER_ORDER = ("quick", "pr", "broad", "smoke", "integration", "slow", "benchmark")
TEST_TIERS = (
    "quick", "pr", "broad", "broad-pr", "smoke", "integration",
    "slow", "benchmark-smoke", "benchmark", "full",
)

TIER_DESCRIPTIONS = {
    "quick": "Small local inner loop for core source, CLI, docs, and tier-contract guards.",
    "pr": "Fast local PR gate; includes quick plus PR-critical deterministic contract modules.",
    "broad": "Broad deterministic modules that are safe but too wide for every local PR edit.",
    "broad-pr": "Broad deterministic pre-merge lane; includes pr plus smoke and integration modules.",
    "smoke": "Focused deterministic smoke lane for hooks, install workflows, host/cross-agent probes, and scale smokes.",
    "integration": "Focused local integration lane for MCP, browser companion, provider routing, sync bundles, and packaging contracts.",
    "slow": "Deterministic but expensive or readiness-heavy tests kept out of normal PR loops.",
    "benchmark-smoke": "Curated public benchmark/support smoke lane.",
    "benchmark": "Full checked-in benchmark test mirror.",
    "full": "Composition of all explicitly classified tests.",
}


def _primary_tier_for_stem(stem: str) -> str:
    if stem in QUICK_STEMS:
        return "quick"
    if stem in PR_STEMS:
        return "pr"
    if stem in SMOKE_STEMS:
        return "smoke"
    if stem in INTEGRATION_STEMS:
        return "integration"
    if stem in SLOW_STEMS:
        return "slow"
    if stem in BENCHMARK_STEMS:
        return "benchmark"
    return "broad"


def _tags_for_stem(stem: str, primary_tier: str) -> tuple[str, ...]:
    tags = {primary_tier}
    if primary_tier in {"quick", "pr", "broad"}:
        tags.add("deterministic")
    if stem.startswith("test_benchmark_"):
        tags.add("benchmark")
    if "smoke" in stem:
        tags.add("smoke")
    if "hook" in stem:
        tags.add("hook")
    if "sync" in stem or "bundle" in stem:
        tags.add("sync")
    if "install" in stem:
        tags.add("install")
    if "provider" in stem or "model" in stem:
        tags.add("provider")
    if "host" in stem:
        tags.add("host")
    tags.update(TAG_OVERRIDES.get(stem, ()))
    return tuple(sorted(tags))


TEST_MODULE_CLASSIFICATIONS = {
    _module_name(stem): TestModuleClassification(
        primary_tier=_primary_tier_for_stem(stem),
        tags=_tags_for_stem(stem, _primary_tier_for_stem(stem)),
    )
    for stem in sorted(TEST_MODULE_STEMS)
}


def validate_manifest(discovered_modules: set[str]) -> None:
    unclassified = sorted(discovered_modules - ALL_TEST_MODULES)
    stale = sorted(ALL_TEST_MODULES - discovered_modules)
    if unclassified or stale:
        details = []
        if unclassified:
            details.append(f"unclassified test modules: {', '.join(unclassified)}")
        if stale:
            details.append(f"stale manifest modules: {', '.join(stale)}")
        raise ValueError("test tier manifest is out of sync; " + "; ".join(details))
