#!/usr/bin/env python3
"""MCP tool catalog schema for AIppocampus."""

from __future__ import annotations

from typing import Any

from conversation_sources import PROVIDER_CHOICES


def tool_schema(
    name: str,
    description: str,
    properties: dict[str, Any],
    required: list[str] | None = None,
    required_any: list[str] | None = None,
) -> dict[str, Any]:
    input_schema: dict[str, Any] = {
        "type": "object",
        "properties": properties,
        "required": required or [],
        "additionalProperties": False,
    }
    if required_any:
        # `required_any` is an AIppocampus readability extension. Mirror it into
        # standard JSON Schema so strict MCP clients do not treat all alternates
        # as optional and discover the error only after a tool call.
        input_schema["anyOf"] = [{"required": [name]} for name in required_any]
        input_schema["required_any"] = required_any
    return {
        "name": name,
        "description": description,
        "inputSchema": input_schema,
    }


TOOLS: list[dict[str, Any]] = [
    tool_schema(
        "agent_recall",
        "Find source-backed continuity routes for the current task. When: prefer over recall_context for semantic, attention-router, macro-aware, or agent-native follow-up recall; use search_memory for exact wording. After: call agent_deepen on the selected route before claims.",
        {
            "cue": {"type": "string"},
            "query": {"type": "string"},
            "intent": {"type": "string"},
            "cwd": {"type": "string"},
            "clean_source_dir": {"type": "string"},
            "registry_dir": {"type": "string"},
            "macro_state_jsonl": {"type": "string"},
            "project": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 25},
            "attention_router": {"type": "boolean"},
            "attention_router_mode": {"type": "string", "enum": ["off", "on", "auto"]},
            "semantic": {"type": "string", "enum": ["off", "auto", "on"]},
            "run_semantic_gate": {"type": "boolean"},
            "semantic_gate_mode": {"type": "string", "enum": ["off", "auto", "on"]},
            "semantic_timeout": {"type": "integer", "minimum": 1, "maximum": 60},
            "include_associative_fallback": {"type": "boolean"},
            "apw_fallback": {"type": "boolean"},
            "apw_sidecar_dir": {"type": "string"},
            "apw_semantic_bridge_path": {"type": "string"},
            "apw_navigation_path": {"type": "string"},
            "apw_active_lock_path": {"type": "string"},
            "apw_feedback_path": {"type": "string"},
            "last_recall_path": {"type": "string"},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
        required_any=["query", "intent", "cue"],
    ),
    tool_schema(
        "agent_aippo",
        "Get low-risk working guidance for a task before editing or broad search. When: use for quick orientation when you do not yet need route receipts. After: run agent_recall or search_memory if the guidance says prior source matters.",
        {
            "task": {"type": "string"},
            "include_private_paths": {"type": "boolean"},
        },
    ),
    tool_schema(
        "agent_background",
        "Surface reviewed background findings for a task cue; does not start background jobs or make findings source truth. When: use for previously reviewed async findings, not live recall. After: reopen source with agent_recall and agent_deepen before claims.",
        {
            "cue": {"type": "string"},
            "query": {"type": "string"},
            "task": {"type": "string"},
            "registry_dir": {"type": "string"},
            "working_memory_path": {"type": "string"},
            "project": {"type": "string"},
            "limit": {"type": "integer", "minimum": 1, "maximum": 12},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
        required_any=["cue", "query", "task"],
    ),
    tool_schema(
        "agent_deepen",
        "Open the selected recall route from agent_recall before quoting or relying on it. When: use after agent_recall request_index or last-recall handles; use recall_deepen for recall_context handles. After: use returned source scope for bounded claims.",
        {
            "handle": {"type": ["string", "object"]},
            "request_index": {"type": "integer", "minimum": 1, "maximum": 25},
            "last_recall": {"type": "boolean"},
            "recall_selector": {"type": "string"},
            "last_recall_path": {"type": "string"},
            "cwd": {"type": "string"},
            "clean_source_dir": {"type": "string"},
            "registry_dir": {"type": "string"},
            "macro_state_jsonl": {"type": "string"},
            "project": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 25},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
        required_any=["handle", "request_index"],
    ),
    tool_schema(
        "agent_explain",
        "Explain why a recall or AIppo route surfaced, without treating it as source evidence. When: use after agent_recall or agent_aippo selection; use recall_diagnostic for no-route, silence, or degradation. After: call agent_deepen if you will rely on the route.",
        {
            "handle": {"type": ["string", "object"]},
            "request_index": {"type": "integer", "minimum": 1, "maximum": 25},
            "last_recall": {"type": "boolean"},
            "recall_selector": {"type": "string"},
            "last_recall_path": {"type": "string"},
            "macro_state_jsonl": {"type": "string"},
            "project": {"type": "string"},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
        required_any=["handle", "request_index"],
    ),
    tool_schema(
        "search_memory",
        "Search clean source for source-backed receipts. When: use exact or distinctive wording; use agent_recall or recall_context for fuzzy continuity. After: reopen with get_turn_context or deepen a route before exact claims.",
        {
            "query": {"type": "string"},
            "scope": {
                "type": "string",
                "enum": ["current", "all_registered_sources", "last_recall_candidates"],
            },
            "cwd": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 25},
            "clean_source_dir": {"type": "string"},
            "registry_dir": {"type": "string"},
            "search_budget": {"type": "string", "enum": ["default", "deep"]},
            "request_index": {"type": "integer", "minimum": 1, "maximum": 25},
            "recall_selector": {"type": "string"},
            "last_recall_path": {"type": "string"},
            "metadata_only": {"type": "boolean"},
            "include_source_snippets": {"type": "boolean"},
            "include_snippets": {"type": "boolean"},
            "include_private_paths": {"type": "boolean"},
        },
        ["query"],
    ),
    tool_schema(
        "recall_context",
        "Get a compact route card for a fuzzy continuity cue. When: prefer over agent_recall for a lightweight route list without semantic or macro diagnostics; use search_memory for exact phrases. After: call recall_deepen on the useful route.",
        {
            "intent": {"type": "string"},
            "query": {"type": "string"},
            "cue": {"type": "string"},
            "cwd": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 25},
            "clean_source_dir": {"type": "string"},
            "registry_dir": {"type": "string"},
            "continuity_domains_snapshot": {"type": "string"},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
        required_any=["intent", "query", "cue"],
    ),
    tool_schema(
        "recall_deepen",
        "Reopen clean source for a route from recall_context or an ambient navigation card. When: use for recall_context handles; use agent_deepen for agent_recall last-recall or request_index routes. After: read the returned source window before claiming.",
        {
            "handle": {"type": ["string", "object"]},
            "cwd": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 25},
            "clean_source_dir": {"type": "string"},
            "registry_dir": {"type": "string"},
            "lock_path": {"type": "string"},
            "continuity_domains_snapshot": {"type": "string"},
            "include_private_paths": {"type": "boolean"},
        },
        ["handle"],
    ),
    tool_schema(
        "recall_diagnostic",
        "Explain why recall surfaced, stayed silent, degraded, or needs source reopen. When: use for recall_context or route/no-route diagnostics instead of agent_explain, which explains a selected agent route. After: run the suggested recall, deepen, or repair action.",
        {
            "cue": {"type": "string"},
            "intent": {"type": "string"},
            "query": {"type": "string"},
            "mode": {"type": "string", "enum": ["why-recall", "why-not-recall"]},
            "cwd": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 25},
            "clean_source_dir": {"type": "string"},
            "registry_dir": {"type": "string"},
            "handle": {"type": ["string", "object"]},
            "thread_id": {"type": "string"},
            "topic_epoch": {"type": "string"},
            "lock_id": {"type": "string"},
            "lock_path": {"type": "string"},
            "cache_path": {"type": "string"},
            "run_semantic_gate": {"type": "boolean"},
            "semantic_gate_mode": {"type": "string", "enum": ["off", "auto", "on"]},
            "semantic_timeout": {"type": "integer", "minimum": 1, "maximum": 60},
            "include_associative_path_diagnostics": {"type": "boolean"},
            "apw_sidecar_dir": {"type": "string"},
            "apw_semantic_bridge_path": {"type": "string"},
            "apw_navigation_path": {"type": "string"},
            "apw_active_lock_path": {"type": "string"},
            "apw_feedback_path": {"type": "string"},
            "include_private_paths": {"type": "boolean"},
        },
    ),
    tool_schema(
        "latest_reply",
        "Find the latest assistant closeout for continuing work; prefer clean source when supplied. When: use to resume thread closeout context, not arbitrary memory search. After: run agent_recall or source reopen on any claim-bearing cue.",
        {
            "cwd": {"type": "string"},
            "rollout": {"type": "string"},
            "clean_source_dir": {"type": "string"},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
    ),
    tool_schema(
        "get_turn_context",
        "Open one clean-source turn by turn_id, message_id, or turn_index from a route. When: use after search_memory, recall_deepen, or a route gives a selector. After: quote only within the returned source scope.",
        {
            "cwd": {"type": "string"},
            "turn_id": {"type": "string"},
            "message_id": {"type": "string"},
            "turn_index": {"type": "integer"},
            "clean_source_dir": {"type": "string"},
            "include_private_paths": {"type": "boolean"},
        },
        required_any=["turn_id", "message_id", "turn_index"],
    ),
    tool_schema(
        "list_threads",
        "List registered local memory threads as route handles, not source evidence. When: use for inventory or debugging before recall, not for answering from memory. After: pass a useful cue to recall_context or agent_recall.",
        {
            "registry_dir": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 100},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_identifiers": {"type": "boolean"},
            "include_private_paths": {"type": "boolean"},
        },
    ),
    tool_schema(
        "register_thread",
        "Register the current thread after explicit consent so future agents can find it. When: use only for an approved local registry write, not read-only recall. After: run memory_health or agent_recall to verify discoverability.",
        {
            "cwd": {"type": "string"},
            "registry_dir": {"type": "string"},
            "build_index": {"type": "boolean"},
            "provider": {"type": "string", "enum": list(PROVIDER_CHOICES)},
            "confirm_write": {"type": "boolean"},
            "write": {"type": "boolean"},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
        ["cwd", "provider", "confirm_write"],
    ),
    tool_schema(
        "sync_status",
        "Check local sync readiness without pushing, pulling, or exposing private paths. When: use before sync push, pull, repair, or object-store setup. After: choose an explicit sync command only if the user wants writes.",
        {
            "cwd": {"type": "string"},
            "sync_dir": {"type": "string"},
            "object_store_url": {"type": "string"},
            "object_prefix": {"type": "string"},
            "token_env": {"type": "string"},
            "include_private_paths": {"type": "boolean"},
        },
    ),
    tool_schema(
        "memory_health",
        "Check whether recall is usable now and get one stable next action. When: use when source or index readiness is uncertain, not as a recall substitute. After: follow foreground_action or run agent_recall when ready.",
        {
            "cwd": {"type": "string"},
            "detail": {"type": "string", "enum": ["compact", "full"]},
            "include_private_paths": {"type": "boolean"},
        },
    ),
    tool_schema(
        "list_telepathy_handoffs",
        "List opt-in Telepathy handoff cards without writing coordination state. When: use when the user asks for saved handoff or coordination cards. After: call deepen_telepathy_handoff for the selected card.",
        {
            "cwd": {"type": "string"},
            "store_path": {"type": "string"},
            "scope": {"type": "string"},
            "status": {"type": "string"},
            "max": {"type": "integer", "minimum": 1, "maximum": 100},
            "include_private_paths": {"type": "boolean"},
        },
    ),
    tool_schema(
        "deepen_telepathy_handoff",
        "Return one Telepathy handoff card with sanitized source selectors for reopen. When: use after list_telepathy_handoffs. After: reopen cited source via get_turn_context or agent_recall before claims.",
        {
            "card_id": {"type": "string"},
            "cwd": {"type": "string"},
            "store_path": {"type": "string"},
            "include_private_paths": {"type": "boolean"},
        },
        ["card_id"],
    ),
]
